//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDCus { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string AddressDeliverry { get; set; }
        public Nullable<decimal> Trigia { get; set; }
        public Nullable<bool> Dagiao { get; set; }
        public Nullable<System.DateTime> Ngaygiaohang { get; set; }
        public string Tennguoinhan { get; set; }
        public string Diachinhan { get; set; }
        public string Dienthoainhan { get; set; }
        public Nullable<bool> HTThanhtoan { get; set; }
        public Nullable<bool> HTGiaohang { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
