//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int IDSP { get; set; }
        public string TenIP { get; set; }
        public string Donvitinh { get; set; }
        public Nullable<int> Dongiabd { get; set; }
        public string HinhSP { get; set; }
        public Nullable<int> star { get; set; }
        public string Cauhinh { get; set; }
        public Nullable<int> Dongia { get; set; }
        public string Hinhminhhoa1 { get; set; }
        public string Hinhminhhoa2 { get; set; }
        public string Hinhminhhoa3 { get; set; }
        public string Hinhminhhoa4 { get; set; }
        public string Screen { get; set; }
        public string HDH { get; set; }
        public string CameraAfter { get; set; }
        public string CameraBefore { get; set; }
        public string Chip { get; set; }
        public string Ram { get; set; }
        public string Rom { get; set; }
        public string Sim { get; set; }
        public string Pin { get; set; }
        public string sale { get; set; }
        public string Feedback { get; set; }
        public string Imgdescription { get; set; }
        public Nullable<int> Soluongban { get; set; }
        public string Category { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
